name: Test R2 Connection

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Test R2 connection
        run: curl -v --max-time 10 https://fac2250073b229f6b4cc8108d73096fe.r2.cloudflarestorage.com
